name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: true
          LANG_COUNT: 8
          BLOCKS: ░▒▓█
          CODE_LANG: txt
